# Site settings
title: Study Area
email: lyb928@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: Poetry and code

# Social icons
facebook: username
linkedin: username
github: Hawaiiguitor
deviantart: username
codepen: username

footer: © Taken theme

# Build settings

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https\://github.com/jneen/rouge#full-options
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
